#-------------------------------
# General Site Settings
title: Jiffy Consulting
logo: logo.svg # You can add own logo.
description: Jiffy Consulting <plz change>


#-------------------------------
# Author Settings
author:
  name: Jiffy Consulting
  image: logo.png
  say-hello: Jiffy Consulting
  bio: We help you do stuff and make stuff that does stuff!

instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
